# Generated by Django 3.2.3 on 2021-06-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(default='utility_images/default.png', upload_to='profile_images/'),
        ),
    ]
